version: 2
references:
  container_config: &container_config
    docker:
      - image: circleci/node:10

jobs:
  build:
    working_directory: ~/music
    <<: *container_config
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.lock" }}
      - run:
          name: install dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.lock" }}
          paths:
            - ~/.local
            - ~/.cache
  test:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: Unit tests
          command: npm run test:unit

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
