version: 2
references:
  container_config: &container_config
    working_directory: ~/music
    docker:
      - image: circleci/node:10

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install dependencies
          command: npm ci
      - run: 
          name: test
          command: npm run test:unit
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
  test:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: Unit tests
          command: echo 'debug' # npm run test:unit see https://discuss.circleci.com/t/node-js-sequential-workflow-example-is-not-working/28152

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
